name: sast-check-runner

run-name: Running static code analysis in pull request @${{ github.actor }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-sast
  cancel-in-progress: true

on:
  pull_request

jobs:
  sast-check-runner:
    uses: cloud-wave/.github/.github/workflows/sast-check.yml@main
    secrets: inherit
