name: Static Code Analysis

on:
  pull_request:
    branches:
      - '*'

jobs:
  sast_check:
      uses: cloud-wave/neonnow-github-workflows/.github/workflows/sast-check.yml@main
      secrets: inherit
