name: Static Code Analysis

run-name: Performing static code analysis in pull request @${{ github.actor }}

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  sast-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'cloud-wave/.github'
          ref: 'main'
          sparse-checkout: |
            config-files/bearer.yml
          sparse-checkout-cone-mode: false
      - run: mv config-files ../
      - uses: actions/checkout@v3
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Bearer
        uses: bearer/bearer-action@v2
        with:
          config-file: "../config-files/bearer.yml"
          diff: true
      - name: Run reviewdog
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -la && ls -la ../ && cat rd.json | reviewdog -f=rdjson -reporter=github-pr-review
