name: Static Code Analysis

run-name: Performing static code analysis in pull request @${{ github.actor }}

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  sast_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'cloud-wave/.github'
          path: 'global-dot-github'
          ref: 'main'
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Bearer
        uses: bearer/bearer-action@v2
        with:
          config-file: "global-dot-github/config-files/bearer.yml"
          diff: true
          skip-path: "global-dot-github"
      - name: Run reviewdog
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat rd.json | reviewdog -f=rdjson -reporter=github-pr-review
